const Aggrement = ({ documentDetails, companyAddress, gstNumber, billingInfo }) => {

  const currentDate = new Date().toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const userInfo = gstNumber
    ? `${companyAddress} [GSTIN: ${gstNumber}]`
    : `${documentDetails.name}${documentDetails.address ? `, ${documentDetails.address}` : ""}${documentDetails.pan ? ` [PAN: ${documentDetails.pan}]` : ` [Aadhar No: ${documentDetails.aadharNo}]`}`;

  return (
    <div className="space-y-4">
      {userInfo && (
        <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-semibold border-b pb-2 mb-2">
          {userInfo}
        </p>
      )}
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        This Merchant Agreement ("Agreement") is between you (company/individual/firm/partnership/body corporate), together with any company or other business entity you are representing, if any (hereinafter collectively referred to as "Merchant" or "you" or "User"); and QUICKPOST, originally known as QUICKPOST360 Services Private Limited, a company registered under the Companies Act, 1956, having its registered office at House No 87 Singhal Panna, Gali No2 Near Shiv Mandir, Badesera, Bhiwani, Bhiwani, Haryana, India, 127031, offering 'Logistics Management Services', under the name QUICKPOST (hereinafter referred to as "QUICKPOST" or "we" or "Company", and together with the User referred jointly as the "Parties" and individually as a "Party").
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">BACKGROUND</p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        This Agreement comes into effect when you register to use the Services (as defined below), or click on "Continue" box, and accept the terms and conditions provided herein.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        By registering or clicking on the 'Continue' box, you signify your absolute, irrevocable and unconditional consent to all the provisions of this Agreement in its entirety. This Agreement constitutes a legally binding agreement between you and QUICKPOST. This Agreement defines the terms and conditions under which you're allowed to use the QUICKPOST's website ("Website") and QUICKPOST's mobile application ("Mobile App"), and how QUICKPOST will treat your account while you are a member. If you have any questions about our terms, feel free to contact us at support@QUICKPOST.in.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        You are advised to read this Agreement carefully. You expressly represent and warrant that you will not avail the Services if you do not understand, agree to become a party to, and abide by all of the terms and conditions specified below. Any violation of this Agreement may result in legal liability upon you.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        The Website/ Mobile App and the online/ offline services of QUICKPOST or its affiliates, provides access to a platform that facilitates more comfortable form of e-commerce where you can use the logistics services according to your requirements within India and in countries designated by QUICKPOST from time to time ("Service(s)").
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        This Agreement, among other things, provides the terms and conditions for use of the Services, primarily through a web-based practice management software hosted and managed remotely through the Website/Mobile App.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        This Agreement is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system, and does not require any physical or digital signatures. This Agreement is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing of the rules and regulations, privacy policy and terms of usage for access or usage of the website/ service.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        QUICKPOST reserves the right to modify the terms of this Agreement, at any time, without giving you any prior notice. Your use of the Service following any such modification constitutes your agreement to follow and be bound by the terms of the Agreement, as modified.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        Any additional terms and conditions, standard operating procedures (SOPs), service-level agreements (SLAs), terms of use, disclaimers and other policies applicable to general and specific areas of this Agreement, Website, Mobile App and/or Service shall be construed to form an integral part of this Agreement and any breach thereof will be construed as a breach of this Agreement.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        Your access to use the Services will be solely at the discretion of QUICKPOST.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">WHEREAS:
      </p>
      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>A.	The Company is engaged in the business of aggregating logistic services. Through itsPlatform, it enables the Customer to ship shipments to multiple locations, without having to directly deal with multiple courier companies (“Logistics Service Provider(s)”) (“Business”).</li>
        <li>B.	The Company has represented to the Customer that it has the relevant expertise, personnel,and skills required to meet the logistic requirements of Customer.</li>
        <li>C.	The Customer is desirous of engaging with the Company and availing the Services (asdefined below), being provided.</li>
        <li>D.	The Parties are desirous of entering into this Agreement to record the terms of theirengagement.</li>
      </ol>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        IT IS AGREED BETWEEN THE PARTIES AS FOLLOWS:
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        1) DEFINITIONS AND INTERPRETATION
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        a. In this Agreement, including in the Recitals hereof, the following words, expressions and abbreviations shall have the following meanings, unless the context otherwise requires::
      </p>

      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>i.	“Agreement” means this Customer Agreement and any Annexures hereto, whether attached
          or incorporated by reference;
        </li>
        <li>ii.	“Applicable Law” shall mean any statute, law, regulation, ordinance, rule, judgment,notification, rule of common law, order, decree, bye-law, government approval, directive, guideline, requirement or other governmental restriction, or any similar form of decision of, or determination by, or any interpretation, policy or administration, having the force of law of any of the foregoing, by any Authority having jurisdiction over the matter in question, whether in effect as of the date of this Agreement or thereafter; iii. “Authority” shall mean any national, state, provincial, local or similar government, governmental, regulatory or administrative authority, branch, agency, any statutory body or commission or any non-governmental regulatory or administrative authority, body or other organization to the extent that the rules, regulations and standards, requirements, procedures or orders of such authority, body or other organization that have the force of Applicable Law or any court, tribunal, arbitral or judicial body, or any stock exchange of the India or any other country;</li>
        <li>iv.	“Confidential Information” shall mean, with respect to each of the Party, informationincluding but not limited to, the business, customers, suppliers, services, products, affairs, performance, marketing plans and finances of each Party, which for the time being is confidential or treated by the Party as such, trade secrets (including technical data and knowhow) relating to the business, suppliers, clients or The Customers;</li>
        <li>v.	“Force Majeure” means an act of god, war, civil disturbance, strike, lockout, act of terrorism,flood, fire, explosion, epidemic, pandemic or legislation or restriction by any government or other authority, or any other similar circumstance beyond the control of any Party, which has the effect of wholly or partially suspending the obligations hereunder, of the Party concerned during the continuance and to the extent of such prevention, interruption or hindrance;</li>
        <li>vi.	“Intellectual Property” or “Intellectual Property Rights” shall mean any and all trademarksand services marks (whether or not registered), copyrights, design rights (whether or not registered), moral rights, patents, performance rights, database rights, internet, WAP and other new media rights, names, logos and codes, publicity rights, and any and all other intellectual property and proprietary rights of any nature whatsoever that subsist, or may subsist, or be capable of registration, in each case in relation to the Services or any part thereof and which exist, or may exist, in any jurisdiction in the territory;</li>
      </ol>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        a. Interpretation
      </p>


      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>i. Headings are used for convenience only and shall not affect the interpretation of Agreement.</li>
        <li>ii. References to this Agreement shall be deemed to include any amendments or modificationsto this Agreement, as the case may be.</li>
        <li>iii. Unless the context specifies otherwise, reference to the singular includes a reference to theplural and vice versa, and reference to any gender includes a reference to all other gender.</li>
        <li>iv. Reference to statutory provisions shall be construed as meaning and including referencesalso to any amendment or re-enactment (whether before or after the date of this Agreement), for the time being in force, all statutory instruments or orders made pursuant to a statutory provision and any statutory provisions of which these statutory provisions are a consolidation, re-enactment or modification.</li>
        <li>v. In addition to the terms defined in this Clause 1, certain other terms are defined elsewhere inthis Agreement and whenever such terms are used in this Agreement, they shall have their respective defined meanings, unless the context expressly or by necessary implication otherwise requires. Provided that in the absence of a definition being provided for a term, word or phrase used in this Agreement, no meaning shall be assigned to such term, word, phrase which derogates or detracts from, in any way, the intent of this Agreement.</li>
      </ol>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        2) ACCOUNT USAGE:
      </p>
      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>i.	This Agreement is a master agreement which governs the relationship between the Parties inrelation to one or more Services that are offered by QUICKPOST to the Customer, inter-alia as per the terms and specifications mentioned and payment as per commercials updated on regular basis on QUICKPOST online panel. QUICKPOST authorizes the Customer to view and access the content available
          on the Website solely for ordering, receiving, delivering and communicating as per this Agreement.
        </li>
        <li>ii.	The contents of the Services, information, text, graphics, images, logos, button icons,software code, design, and the collection, arrangement and assembly of content on the Website and Mobile App (collectively, "QUICKPOST Content"), are the property of QUICKPOST and are
          protected under copyright, trademark and other laws. User shall not modify the QUICKPOST Content or reproduce, display, publicly perform, distribute, or otherwise use the QUICKPOST Content in any manner,
          without the consent of QUICKPOST.
        </li>
        <li>iii.	Customer shall not transfer or share (including by way of sublicense, lease,assignment orother transfer, including by operation of law) their log-in or right to use the Service to any third party. The Customer shall be solely responsible for the way anyone it has authorized to use the Services and for ensuring that all of such customer comply with all of the terms and conditions of this Agreement. Any violation of the terms and/or conditions of this Agreement by any such customer shall be deemed to be a violation thereof by you, towards which QUICKPOST shall have no liability or responsibility.</li>
        <li>iv.	Multiple users are not permitted to share the same/single log-in. You agree and understandthat you are responsible for maintaining the confidentiality of passwords associated with any log-in you use to access the Services;</li>
        <li>v.	Customer agree that any information it gives to QUICKPOST will always be true, accurate,
          correct, complete and up to date, to the best of its knowledge. Any phone number used to register with supporting documents to prove the same.
        </li>
        <li>vi. Customer agrees that you will not use the Services
          provided by QUICKPOST for any unauthorized and unlawful purpose. The Customer will not impersonate another person to any of the aforesaid. </li>
        <li>vii. Customer agrees to use the Services only for purposes that are permitted by: (a)the
          terms of usage as outlined herein; and (b) any applicable law, regulation and generally accepted practices or guidelines in the relevant jurisdictions (including any laws regarding the export of goods, data or software to and from India or other relevant countries). </li>
        <li>viii. Customer agrees that it is solely responsible for (and that QUICKPOST has no responsibility to
          the
          Customer or to any third party for) any breach of Customer’s obligations under this Agreement and for the consequences (including any loss or damage which QUICKPOST may suffer) of any
          such breach.
        </li>
        <li>ix.	Customer expressly acknowledges and agrees that the use of the Services is at Customer’ssole risk and that the Services are provided “as is” and “as available”, and QUICKPOST at its discretion, will provide any customization or modification.</li>
        <li>x.	Customer agrees that this Agreement and the Services of QUICKPOST form a part of subject to
          any modification or be removed by QUICKPOST with change in government regulations, policies and local laws as applicable.
        </li>
        <li>xi.	Customer agrees not to access (or attempt to access) any of the Services by any meansother than through the interface that is provided by QUICKPOST, unless you have been specifically allowed to do so in a separate agreement with QUICKPOST.</li>
        <li>xii.	Customer agrees that you will not engage in any activity that interferes with or disrupts theServices (or the servers and networks which are connected to the Services).</li>
        <li>xiii.	Customer agrees that you are solely responsible for (and that QUICKPOST has noresponsibility to
          you or to any third party for) any breach of your obligations under this Agreement
        </li>
      </ol>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        3) SERVICES BEING PROVIDED BY THE COMPANY TO THE CUSTOMER
      </p>

      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>i. With effect from the Effective Date, the Customer hereby appoints the Company, to provide consequences (including any loss or damage which QUICKPOST may sulogistics solutions in accordance with the terms and conditions of this Agreement (“Services”).ffer) of any such breach</li>
        <li>ii.	In order to avail the Services, the Customer is required to create an account at the Platform(“User Account”), by providing all the relevant, true, accurate, current and complete details, as detailed in (which includes- GST registration in case of registered customer, Pan, TAN, COI in case of company, Cancelled cheque of bank account as per KYC).</li>
        <li>iii.	Customer agrees that no fake, inaccurate or incomplete details of the Customer shall beprovided to QUICKPOST as part of the KYC process set out above. In case the Customer fails to provide
          complete and accurate details to the Company as part of the KYC process, such act or omission shall be considered a material breach of this Agreement and QUICKPOST has the right to recover from the Customer, damages and any and all losses suffered by it on account of such incomplete or inaccurate KYC details provided by the Customer.
        </li>
        <li>iv.	Customer is mandatorily required to give full address of shipping location/warehouses fromwhere the shipment is required to be picked and address should be updated at place of business or additional place of business in statutory registrations as applicable.</li>
        <li>v.	The Customer shall also be required to assign itself, a username and password to access theUser Account.</li>
        <li>vi.	The Customer hereby agrees that it shall be responsible for maintaining the confidentiality ofuser name and password and the transactions occurring in its User Account.</li>
        <li>vii.	The Customer agrees and acknowledges that it shall be required to process/ place a requestfor its logistics requirement on the Platform. Upon receiving the request, the Company shall assign a Logistics Service Provider, who shall pick up the shipment from the location provided by the Customer. The Company shall assign a Logistics Service Provider, at its sole discretion and such assignment of a Logistics Service Provider shall be based on the location of the Customer, nature of the consignment, etc.</li>
        <li>viii.	The Customer shall be required to clearly provide on the Platform, the details of theconsignment, including but not limited to consignment details, consignee details, return address/ shipping address, amount of money to be collected in case of cash on delivery (“COD”) shipments etc The details of the bank account, where any money is collected as part of the COD, should also be provided on the Platform. Any bank account details provided for collection of COD should match the copy of the cancelled cheque submitted by the Customer. In case of revision of bank account revised cancelled cheque will need to be provided. The customer also certifies and confirms that the bank accounts provided are for legitimate business purposes and are legally permitted to receive monies collected by the Company for such shipment/s for which the Company received COD.</li>
        <li>ix.	The duly packaged consignment shall be handed over to the Logistics Service Provider bythe Customer, along with the aforementioned details on the packaging.</li>
        <li>x.	Customer agrees that tax invoice shall be issued as per GST compliances and copy of thesame shall be attached in shipment. Customer can use the feature of Add on services of QUICKPOST
          on seller panel and generate invoice from the same. In both the scenario, QUICKPOST has no involvement in the invoicing and not liable for the same. Customer shall be only liable for the same.
        </li>
        <li>xi.	In case of COD consignments, the Logistics Service Provider shall collect the amount ofmoney from the consignee, as per the instructions provided by the Customer. The Logistics Service Provider shall remit such money to the bank account of the Company, after the same being collected from the consignee. The Company shall thereafter remit the COD amount so received from the Logistics Service Provider to the bank account of the Customer as notified by the Customer on the Platform and as per any other terms agreed between the QUICKPOST and Customer. However, the Company shall not be held liable in case the COD payments are delayed or misplaced by the Logistics Service Provider. Upon receipt of the COD payments from the Logistics Service Provider by the Company and remittance of the same by the Company to the aforementioned bank account notified by the Customer, the Company shall have no liability towards the Customer for the collection or recovery of such COD payments. Further, once the details of relevant bank account have been notified to the Company by the Customer, the Company shall have no further obligation to verify the veracity and genuineness of the notification by the Customer, or to undertake any further due diligence or KYC process on the signatories of such bank account. However, the Company shall have the right to conduct a KYC on such bank account for its records.</li>
        <li>xii.	The Customer shall be required to raise any concerns/ queries, (i) with respect to a lostconsignment, within a period of 15 days from sending the consignment; and (ii) with respect to any damage, default or any other concerns with respect to the consignment, within a period of 7 days from delivery/ reverse delivery of the consignment. xiii. The Customer shall be provided with a tracking number (AWB number) by the Company for the consignment. The Customer can track the consignment, on a real time basis using the tracking number provided.</li>
        <li>xiii. The Customer shall be provided with a tracking number (AWB number) by the Company for the consignment. The Customer can track the consignment, on a real time basis using the tracking number provided.</li>
        <li>The Customer agrees and acknowledges that it shall be responsible for paying all duties, taxes, any other charge/levy that may be levied on consignment under Applicable Law. </li>
        <li>xv. The Customer hereby agrees that the Company is only an intermediary between the Customer and the Logistics Service Provider. In the event of a dispute between the Customer and the Logistics Service Provider, the Company shall take all reasonable steps to try and ensure an amicable settlement between the Customer and the Logistics Service Provider. In the event of a settlement between the Customer and the Logistics Service Provider, the Company’s obligation shall be to merely pass on any damages provided by the Logistics Service Provider to the Customer, as per the individual terms and conditions of the Logistics Service Provider. However, the Company shall not be liable in the event the Customer and the Logistics Service Provider are unable to reach an amicable settlement. Further, the Company shall not be liable for any costs/ damages/ claims arising from or in relation to such dispute between the Customer and the Logistics Service Provider.</li>
        <li>Customer agrees that no fake products/goods will be delivered to the end consumer and if any fake product is found then QUICKPOST has the right to pay the amount to end customer and same
          shall be recovered from Customer. Any cost , expense in relation to that issue will be received from the customer or deducted from COD amount . In addition to this, Customer shall be liable for prosecution and penalty of Rs 100,000/- or Goods value whichever is higher if found to be in delivering any illegal or fake products/Goods. </li>
        <li>xvii. Customer agrees that if there is any quality issue with the end consumer then QUICKPOST has
          the right to pay the amount to end consumer and same shall be received from the customer.</li>
        <li>xviii. Customer agrees that it is solely responsible for any breach of Customer obligations under this Agreement and for the consequences of any such breach.</li>
        <li>xix. In consideration of the Services rendered by Company, the Customer agrees to pay to the Company, the consideration in accordance with Clause 4 of this Agreement.</li>
      </ol>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed font-bold">
        4) FEES / CONSIDERATION AND PAYMENT
      </p>

      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>i.	In consideration of the Company providing the Services to the Customer, the Customer agreesto pay the Company, valid consideration, the details of which are mentioned on Billing section on QUICKPOST online panel to this Agreement (“Consideration”) or in the billing section of the
          QUICKPOST panel. In addition to the Consideration, the Customer shall also be required to pay applicable fees for shipping the consignment, which shall again be provided on the billing section of Shiproxx
          India panel to this Agreement (“Shipping fees")
        </li>
        <li>ii.	The Consideration specified in this Agreement is exclusive of all applicable taxes. TheCustomer shall be required to pay applicable goods and service tax and fuel surcharge etc. The same shall be stated as separate items in the invoice raised by the Company on the Customer on or before 07th of the succeeding month for the Services that have been rendered in previous month as per the terms of this Agreement.</li>
        <li>iii.	QUICKPOST may add new services for additional fees and charges or may proactively amendfees and charges for existing services, at any time in its sole discretion. Fees stated prior to the services being provided, as amended at QUICKPOST’s sole discretion from time to time, shall apply.</li>
        <li>iv.	If you purchase any subscription based paid service, you authorize QUICKPOST to charge youapplicable fees at the beginning of every subscription period or at such intervals as applicable to the said service, and you authorize QUICKPOST make such modification to the fee structure as required and also agree to abide by such modified fee structure.</li>
        <li>v.	Customer agrees that the billing credentials provided by it for any purchases from QUICKPOST
          will be accurate and the Customer shall not use billing credentials that are not lawfully owned by it.</li>
        <li>vi. The Customer agrees to pay all subscription fees, service fees and other fees applicable to User’s use of Services or any other services which are beyond the scope of the Services and/or this Agreement, and the User shall not (directly or indirectly) circumvent the fee structure.</li>
        <li>vii.	The User is solely responsible for payment of all taxes, legal compliances, and statutoryregistrations and reporting under applicable law. QUICKPOST is in no way responsible for any of the
          User’s taxes or legal or statutory compliances.
        </li>
        <li>viii.	Unless otherwise specified, all fees shall be exclusive of taxes, and Goods and Service taxand other statutory taxes, as applicable, shall be levied on every purchase/Service.</li>
        <li>ix.	The Customer may also use the prepaid mode of payment of Consideration and Shipping Fees.</li>
        <li>x.	The Company shall issue an invoice to the Customer on or before 07th of each succeedingmonth for the Services that have been rendered in previous month as per the terms of this Agreement.</li>
        <li>xi.	The Customer shall pay to the Company within Seven (7) days from the date of submissionof the invoice as per commercials updated on the billing section of the QUICKPOST panel. </li>
        <li>xii. It will be the responsibility of the Customer to verify the invoices and inform the Company within 5 (five) days in case of any disputes regarding the contents of the invoice from the date of receipt of invoices. Thereafter, the Parties shall promptly seek to resolve the dispute in good faith. Payment of the undisputed amount shall not be affected and should be made as per the general terms of this Agreement.</li>
        <li>xiii.	If for any reason the Customer defaults in making the payments against undisputedInvoices issued by Service Provider, then the Service Provider shall have the right to invoke the dispute resolution as set out under the Agreement.</li>
        <li>xiv.	If the User fails to pay the full invoice amount in accordance with the time period mentionedabove or any other amounts/charges payable under this Agreement by the due date, then QUICKPOST will have the right to: (i) retain (and subsequently adjust the outstanding amounts/charges within 30 days of retention from) the amounts received from the end customer of the User through the cash on delivery method (“COD Amount”), and/or (ii) retain the custody of (and subsequently dispose within 30 days of retention) the shipments of the User which are in the possession of QUICKPOST logistics partner(s), and/or (iii) levy an interest of 18% per annum from
          the due date of payment, till such time that the User makes entire payment towards the invoice, and/or (iv) forfeit the security deposit amount of the User (if any) lying with QUICKPOST. Without
          being
          prejudice to the above, the User hereby agrees that it shall become liable to pay the freight charges (both forward and RTO charges) as soon as a shipment is picked up or is RTO initiated by the QUICKPOST courier partner, and that QUICKPOST shall have a right to recover such freight charges
          from the User (for all the shipments which have been picked-up/shipped/RTO however which have not been invoiced) as per the various modes agreed under this Agreement, including but not limited to retaining/adjusting the COD Amounts for the shipments of the User. The Company shall release such consignments and/or COD shipment payments, only upon the Customer paying the Consideration owed to the Company.
        </li>
        <li>xv.	The Company reserves its right to revise the Consideration payable by the Customer, byproviding a prior written notice of 7 days to the Customer. The Customer shall be required to raise any concerns pertaining to the same within a period of 4 days from the date of receiving such notice. In the event, the Customer fails to raise any concern within the stipulated time period, the revised Consideration shall deemed to be accepted by the Customer. In the event the Customer raises any concerns within stipulated time period, the Parties shall negotiate and determine the revised Consideration. Such revised Consideration shall be effective, upon the expiry of the notice period.</li>
        <li>xvi.	In the event the User closes its account with the Company, or this Agreement expires or isterminated, the Company will deduct the Consideration and Shipping Fees and the freight amounts due to it from the User, from the COD Amount. The Company shall, thereafter, remit the remaining COD amount after such deduction, within 45 (Forty-Five) business working days from the date of such closure/expiration/termination, subject to reconciliation and completion of all the shipments and transactions pertaining to the User/his account. In the event, the COD Amount falls short of the outstanding amount payable by the User, the User shall within 5 (five) days from the date of such closure/expiration/termination pay the outstanding amount to the Company, and until the payment of the entire outstanding amount, the Company shall retain the custody of the shipments of the User which are in the possession of Logistics Service Provider. In the event of any delay in payment of outstanding amount by the User (as required under this clause), QUICKPOST shall have a right to levy an interest of 18% per annum on the outstanding amount from the due date of payment till the date of actual payment and/or to forfeit the security deposit amount of the User (if any) lying with QUICKPOST.</li>
        <li>xvii.	For any claims by the User regarding non connectivity of the shipment (i.e.where the Useris claiming that the shipment has been picked up but not connected) the signed copy of the manifest sheet of the pick up against the disputed shipment has to be submitted along with the claim request by the User within 3 (three) days from the pickup date. Without the signed manifest any such request shall not be considered valid. QUICKPOST shall be liable for forward &
          RTO
          delivery subject to the liability of Rs 5,000 (Rupees Five thousand only) in case of forward delivery and if loss or damage is in excess of Rs 5,000 than QUICKPOST shall issue COF (Certificate
          of
          Facts) govern by Limitation of Liability clause.
        </li>
        <li>xviii.	The User agrees that in case of shipments booked under Cash on Delivery(“COD”), Logistics
          Service Provider shall collect cash, as per the instructions of QUICKPOST from the consignee as per the
          details mentioned on the COD order form and remit/reimburse the amount to QUICKPOST which
          then forthwith would be reimbursed to the User. However, QUICKPOST shall not be held liable in case the
          COD amount has been delayed or misplaced by the courier company. The User shall seek its claim, loss or any damages suffered from the Logistics Service Provider directly, and in no way shall recover from QUICKPOST or hold QUICKPOST liable for the same. In this regard, the User
          agrees that
          QUICKPOST shall have the right to deduct the freight charges from the COD Amounts received by QUICKPOST, and then remit/reimburse the balance amount to the User. xx. QUICKPOST may, from time to time, in its sole discretion, provide/allocate a credit limit to the
          User
          for the Services, which can be used by the User within a specified time period. In this regard, the User hereby acknowledges and agrees to pay the service fees and all other amounts (payable by it pursuant to this Agreement), and in the event User fails to timely pay the same, QUICKPOST shall have an unconditional and irrevocable right, in addition to other rights and
          remedies
        </li>
        <li>xix.	QUICKPOST reserves the right to modify the fee structure by providing a notice, either on yourdashboard or through email to the authorized User, which shall be considered as valid and agreed communication. Upon the User not communicating any negative response/objection to QUICKPOST to such notice, QUICKPOST shall apply the modified Fee structure.</li>
        <li>xxi.	In order to process the fee payments, QUICKPOST might require details of User’s bank account, credit card number and other such financial information. Users shall be responsible to maintain the confidentiality of such information provided by Users.</li>
      </ol>



      <p className="text-xs font-bold sm:text-sm text-gray-700 leading-relaxed">5) LIMITATION OF LIABILITY AND DISCLAIMERS:</p>
      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed space-y-2">
        <li>
          i. In case of loss or damage up to Rs 5,000 (Rupees five thousand only), the total aggregate liability of QUICKPOST shall be Rs 5,000 or actual loss, whichever is lower. If damage or loss exceeds Rs 5,000, then QUICKPOST shall issue a Certificate of Facts (COF) only.
        </li>
        <li>
          ii. Under any circumstances, the company shall not be liable to the customer in any amount for special, incidental, consequential, or indirect damages, loss of goodwill or business profits, work stoppage, or exemplary or punitive damages.
        </li>
        <li>
          iii. The Customer agrees and acknowledges that the use of the Services is at its sole risk and that the Services are provided "AS IS" by QUICKPOST.
        </li>
        <li>
          iv. The Company shall not be responsible or liable in any manner to the Customer for any losses, damage, or expenses incurred by the Customer as a result of any action taken by the Company, where the Customer has consented to the same.
        </li>
        <li>
          v. The Company does not provide or make any representation, warranty, or guarantee, express or implied, about the Services. The Company does not verify any content or information/details provided by the Customer, and to the fullest extent permitted by applicable law, the Company disclaims all liability arising out of the Customer’s use of the Services.
        </li>
        <li>
          vi. The Logistics Service Providers are not controlled by the Company, and the Company shall not be liable for any loss, damage, destruction, or delay in delivery/pickup of the consignment by them except as mentioned in clause 5 (i) above. The Company shall not be responsible for any actions or inactions of the Logistics Service Providers.
        </li>
        <li>
          vii. The Company shall, in no manner, be liable to remit the Cash-on-Delivery (COD) that is to be received as payment by the User in case of theft, robbery, or forcible snatching of the delivery package from the Logistics Service Provider. Such incidents shall be the sole responsibility of the User, and the User is liable to initiate actions to resolve such incidents, including legal proceedings and reimbursement of any losses to the concerned logistics partner or its personnel.
        </li>
        <li>
          viii. In no event, including but not limited to negligence, shall QUICKPOST or any of its directors, officers, employees, agents, or service providers (collectively, the “Protected Entities”) be liable for any direct, indirect, special, incidental, consequential, exemplary, or punitive damages arising from, or directly or indirectly related to, the use of, or the inability to use, the Services or the content, materials, and functions related thereto, including lost business or lost sales, even if such Protected Entity has been advised of the possibility of such damages.
        </li>
        <li>
          ix. In no event shall the total aggregate liability of the Protected Entities/Service Provider(s) to a User for all damages, losses, and causes of action (whether in contract or tort, including but not limited to negligence or otherwise) arising from the terms and conditions of this Agreement or a User’s use of the Services exceed INR 5,000 (Indian Rupees Five Thousand) only. In case of loss or damage exceeding Rs 5,000, QUICKPOST shall issue a Certificate of Facts (COF) only.
        </li>
        <li>
          x. The Protected Entities shall not be liable for any act or omission of any other person or entity furnishing a portion of the Service, or from any act or omission of a third party, including vendors participating in the Services, or for any unauthorized interception of communications or other breaches of privacy attributable in part to the acts or omissions of the User or third parties.
        </li>
        <li>
          xi. For shipments booked through “Delhivery,” if the delivery (forward) percentage for the shipments booked through “Delhivery” falls below 60% of the total shipments booked, there will be no lost and damage claims entertained by the company.
        </li>
      </ol>


      <p className="text-xs font-bold sm:text-sm text-gray-700 leading-relaxed">6) REPRESENTATIONS, WARRANTIES AND COVENANTS</p>

      <ol className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed list-decimal space-y-2 ml-4">
        <li>
          <span className="font-semibold">The Company hereby represents, warrants, and covenants to the Customer that:</span>
          <ul className="list-[lower-alpha] ml-6 space-y-1">
            <li>it is a validly incorporated business entity;</li>
            <li>it has the facilities and resources required to discharge and shall discharge the Services in a timely and efficient manner;</li>
            <li>this Agreement does not conflict with any of its existing contracts.</li>
          </ul>
        </li>

        <li>
          <span className="font-semibold">The Customer hereby represents, warrants, and covenants to the Company that:</span>
          <ul className="list-[lower-alpha] ml-6 space-y-1">
            <li>it is a validly incorporated business entity or is legally competent to contract, as applicable;</li>
            <li>it shall use the Services being provided by the Company only for lawful purposes;</li>
            <li>it shall at all times abide by the terms and conditions mentioned in this Agreement;</li>
            <li>it shall fulfill all the obligations as mentioned in this Agreement;</li>
            <li>it agrees and understands that the Company is only an intermediary between itself and the Service Provider(s);</li>
            <li>
              it agrees and acknowledges that the Company shall not be liable for any loss, damage, destruction, or delay in delivery/pickup of the consignment. It further agrees and acknowledges that the Company shall not be responsible for any actions or inactions of the Service Provider(s);
            </li>
            <li>the Company shall not be responsible for but reserves its right to check the contents of the consignment being handed over by the Customer or the consignee to the Service Provider.</li>
          </ul>
        </li>

        <li>
          <span className="font-semibold">Each Party represents and warrants to the other Party that:</span>
          <ul className="list-[lower-alpha] ml-6 space-y-1">
            <li>it has all necessary rights, powers, and authority to enter into and perform this Agreement;</li>
            <li>the execution and performance of this Agreement by it shall not violate any Applicable Law and shall not breach any agreement, covenant, court order, judgment, or decree to which such party is bound.</li>
          </ul>
        </li>
      </ol>



      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">7) INDEMNITY</p>
      <p className="text-gray-700 text-[10px] sm:text-[12px]">
        <span className="font-semibold">i.</span> The Customer (“Indemnifying Party”) hereby agrees to indemnify, defend, and hold QUICKPOST,
        its affiliates, officers, directors, employees, contractors, sub-contractors, consultants, licensors, other third-party service providers,
        agents, and representatives (“Indemnified Party”) harmless from and against claims, demands, actions, liabilities, costs, interest, damages, and expenses
        of any nature whatsoever (including all legal and other costs, charges, and expenses) incurred or suffered (directly or indirectly) by the Indemnified Party, on account of:
      </p>
      <ul className="list-[lower-alpha] ml-6 space-y-1 text-[10px] sm:text-[12px] text-gray-700">
        <li>Indemnifying Party’s access to or use of Services;</li>
        <li>violation of this Agreement or any terms of use of the Services by the Indemnifying Party (and/or its officers, directors, and employees);</li>
        <li>violation of applicable law by the Indemnifying Party (and/or its officers, directors, and employees);</li>
        <li>wrongful or negligent act or omission of the Indemnifying Party (and/or its officers, directors, and employees);</li>
        <li>any third-party action or claim made against the Indemnified Party due to actions undertaken by the Indemnifying Party;</li>
        <li>any duties, taxes, octroi, cess, clearance charges, and any other charges levied on the shipments.</li>
      </ul>
      <p className="text-gray-700 text-[10px] sm:text-[12px]">
        <span className="font-semibold">ii.</span> The Company will notify the User promptly of any such claim, loss, liability, or demand. In addition, the User agrees to provide
        the Company with all reasonable assistance, at the User’s expense, in defending any such claim, loss, liability, damage, or cost.
      </p>

      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">8) FACILITATOR</p>
      <p className="text-gray-700 text-[10px] sm:text-[12px]">
        Customer acknowledges that the Company’s role under this Agreement is limited to providing Services to facilitate transactions between the Customer
        and the Logistics Service Provider. The Company is merely a facilitator. The transaction for sale of any products is a bipartite contract between
        Customer and the consignee. The Company shall neither have any obligations or liabilities regarding such contract nor hold any rights, title, or interest in the products sold by the Customer. The Company will also not be responsible for unsatisfactory performance, actions, or omissions by the Customer, including delays, defects, or incorrect information.
      </p>

      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">9) COMPLIANCE WITH LAWS</p>
      <p className="text-gray-700 text-[10px] sm:text-[12px]">
        Each Party agrees to comply with all applicable local laws, ordinances, and codes in fulfilling its obligations under this Agreement. If, at any time during the term of this Agreement, a Party is informed or becomes aware of a potential violation of any law, regulation, or code, that Party shall promptly take all necessary steps to rectify the issue and ensure full compliance. Further, each Party shall establish and maintain all proper records (including but not limited to accounting records) as required by any applicable laws, codes, or policies.
      </p>

      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">10) CONFIDENTIALITY</p>
      <p className="text-gray-700 text-[10px] sm:text-[12px]">
        Each Party may receive Confidential Information from the other Party in order to perform its obligations under this Agreement. The Party receiving such information shall be referred to as the “Receiving Party,” while the disclosing entity shall be known as the “Disclosing Party.”
      </p>
      <ul className="list-decimal ml-6 space-y-1 text-[10px] sm:text-[12px] text-gray-700">
        <li>
          Both Parties shall keep confidential any Confidential Information and ensure that their officers, employees, agents, affiliates, and professional advisers also maintain confidentiality. This information shall be used solely for the provision of services and performance under this Agreement.
        </li>
        <li>
          <span className="font-semibold">Exceptions:</span>
          <ul className="list-[lower-alpha] ml-6 space-y-1">
            <li>Information independently developed by a Party or acquired from a third party without breaching this Clause.</li>
            <li>Disclosure required by applicable law, government authority, stock exchange rules, or a binding judgment, order, or regulation.</li>
            <li>Information that is already within the public domain (excluding disclosures resulting from a breach of this Clause).</li>
          </ul>
        </li>
        <li>
          Both Parties shall inform their officers, employees, agents, and professional advisers about the confidentiality obligations and instruct them to maintain confidentiality.
        </li>
        <li>
          Upon termination or expiration of this Agreement, all Confidential Information must be returned or destroyed as per the Disclosing Party’s instructions, with written confirmation of such action.
        </li>
        <li>
          However, nothing herein shall restrict either Party from using or disclosing its own Confidential Information in any manner.
        </li>
      </ul>



      <ol className="text-xs text-gray-700 sm:text-sm leading-relaxed list-decimal space-y-2 ml-1">

        
          <span className="font-semibold text-[10px] sm:text-[12px]">11) INTELLECTUAL PROPERTY RIGHTS:</span>
          <ul className="list-[lower-alpha] ml-2 space-y-1 text-[10px] sm:text-[12px]">
            <li>
              The Customer acknowledges that the Company is, and shall be the sole owner of all Intellectual Property Rights in and to any solutions and/or products that have been developed by the Company, so as to enable it to render Services to the Customer.
            </li>
            <li>
              Both the Parties acknowledge that any Intellectual Property Rights already owned by the other Party shall remain the sole property of such other Party. However, so as to enable each Party to perform their obligations under this Agreement, the Parties acknowledge that they shall be required to make available to the other Party, a part of their Intellectual Property Rights. Accordingly, as and when required, each Party shall grant to the other Party, a non-transferable license to use their Intellectual Property Rights for the purpose of this Agreement only.
            </li>
            <li>
              The Parties recognize that all third-party Intellectual Property Rights are the exclusive property of their respective owners. The Company shall inform the Customer of any third-party Intellectual Property Rights that may be required to perform the Services required under the terms of this Agreement. Under such circumstances, both Parties shall seek to procure appropriate licenses to use such Third-Party Intellectual Property Rights from the owner of such Third-Party Intellectual Property Rights.
            </li>
          </ul>
        

        
          <span className="font-semibold text-[10px] sm:text-[12px] mt-2">12) NON-SOLICITATION:</span>
          <ul className="list-[lower-alpha] ml-2 space-y-1 text-[10px] sm:text-[12px]">
            <li>
              The User agrees and undertakes that, during the term of this Agreement, and for a period of 36 (thirty-six) months thereafter, it shall not directly or indirectly attempt in any manner to solicit, any client/customer, or to persuade any person, firm or entity which is a client/customer/supplier/vendor/partner of QUICKPOST, to cease doing business or to reduce the amount of business which any such client/customer/supplier/vendor/partner has customarily done or might propose doing with QUICKPOST.
            </li>
          </ul>
        

        
          <span className="font-semibold text-[10px] sm:text-[12px] mt-2">13) TERMS, TERMINATION, AND DISPUTES:</span>
          <ul className="list-[lower-alpha] ml-2 space-y-1 text-[10px] sm:text-[12px]">
            <li>
              The Agreement shall come into force with effect from the Effective Date and shall remain in place until terminated by either Party in accordance with the provision of this agreement.
            </li>
            <li>
              The Customer can request for termination of his/her/its membership with QUICKPOST at any time with a 30 days prior written notice subject to the provisions for the Services undertaken. During this notice period, QUICKPOST will investigate and ascertain the fulfillment of any ongoing Services or pending dues related to fees or any other payables by the Customer. The Customer shall be obligated to clear any dues with the Company for any of its Services which the Customer has procured. QUICKPOST shall not be liable to the Customer or consignee or any third party for any termination of the Customer access to the Services.
            </li>
            <li>
              QUICKPOST reserves the right to terminate the Customer’s User Account in case:
              <ul className="list-[lower-roman] ml-6 space-y-1">
                <li>The Customer breaches any terms and conditions of this Agreement.</li>
                <li>
                  The Company believes in its sole discretion that the Customer’s actions may cause legal liability for itself, other customers, or for the Company or are contrary to the Terms of Use of the Services as provided on the Platform.
                </li>
              </ul>
            </li>
            <li>
              QUICKPOST may terminate the Agreement by giving 10 days prior written notice to the Customer.
            </li>
            <li>
              In case of dispute between the parties, the Customer hereby agrees to negotiate in good faith to resolve any dispute between them regarding this Agreement. If the negotiations do not resolve the dispute to the reasonable satisfaction of the parties, then each party shall nominate a person with respectable professional standing and unimpeachable conduct as its representative. These representatives shall, within 30 (thirty) days of a written request by either party to call such a meeting, meet in person and shall attempt in good faith to resolve the dispute.
            </li>
            <li>
              Notwithstanding anything contained in this agreement, either party shall give prior termination notice of at least 30 days (thirty) to the other party.
            </li>
          </ul>
        

      
          <span className="font-semibold text-[10px] sm:text-[12px]">14) CONSEQUENCES OF TERMINATION:</span>
          <ul className="list-[lower-alpha] ml-2 space-y-1 text-[10px] sm:text-[12px]">
            <li>
              Upon termination of this Agreement, any rights or authority granted by either Party to the other Party shall terminate with immediate effect and all payments accrued before or on the effective date of termination will become immediately due and payable.
            </li>
            <li>
              The accrued rights of the Parties as at termination, or the continuation after termination of any provision expressly stated to survive or implicitly surviving termination, shall not be affected or prejudiced in any manner.
            </li>
            <li>
              All the Confidential Information exchanged between the Parties during the Term of this Agreement shall be either returned to the disclosing party or destroyed by the receiving party within a period of five (5) days from the date of termination.
            </li>
            <li>
              In the event the Customer closes its account with the Company, or this Agreement expires or is terminated, the Company will deduct the Fees and the freight amounts due to it from the Customer from the COD Amount. The Company shall, thereafter, remit the remaining COD Amount after such deduction, within 45 (Forty-Five) business working days from the date of such closure/expiration/termination, subject to reconciliation and completion of all the shipments and transactions pertaining to the Customer/its account. In the event, the COD Amount falls short of the outstanding amount payable by the Customer, the Customer shall within 5 (five) days from the date of such closure/expiration/termination pay the outstanding amount to the Company, and until the payment of the entire outstanding amount, the Company shall retain the custody of the shipments of the Customer which are in the possession of the Company or its Logistics Service Providers. In the event of any delay in payment of outstanding amount by the Customer (as required under this clause), the Company shall have a right to levy an interest of 18% per annum on the outstanding amount from the due date of payment till the date of actual payment and/or to forfeit the security deposit amount of the Customer (if any) lying with the Company.
            </li>
          </ul>
        


        <p className="font-semibold text-[10px] sm:text-[12px]">15) ABUSE OR MISUSE OF SERVICES:</p>
        <ul className="list-[lower-alpha] ml-2 space-y-1 text-[10px] sm:text-[12px]">
          <li>
            The Company may restrict, suspend, or terminate the account of any User who abuses or misuses the Services. Misuse includes creating multiple or false profiles, infringing any Intellectual Property rights, violating any of the terms and conditions of this Agreement, or any other behaviors that with the Company, in its sole discretion, deems contrary to its purpose.
          </li>
          <li>
            In addition, the Company may also restrict, deactivate, suspend or terminate the account of any User upon the request/instructions of the Logistics Service Provider.
          </li>
          <li>
            The Company may also impose a penalty of Rs 100,000/- or the amount involved in misuse of services, whichever is higher.
          </li>
        </ul>


      </ol>

      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">16) SEVERABILITY</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700">The invalidity or unenforceability of any provision in this Agreement shall in no way affect the validity or enforceability of any other provision herein. In the event of the invalidity or unenforceability of any provision of this Agreement, the Parties will immediately negotiate in good faith to replace such a provision with another, which is not prohibited or unenforceable and has, as far as possible, the same legal and commercial effect as that which it replaces.</p>
      <p className="text-[10px] sm:text-[12px] font-bold text-gray-700">17) FORCE MAJEURE:</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700">i.	In the event either Party (the “Prevented Party”) is prevented from performing itsobligations(except payment for the services utilized or agreed fixed cost, if any) under this Agreement by force majeure, such as earthquake, typhoon, flood, public commotion, torrential rains, heavy winds, storms or other acts of nature, fire, terrorist acts, threatened terrorists acts, explosion, acts of civil or military authority including the inability to obtain any required approvals or permits, strikes, riots, war, plagues, other epidemics, pandemics or other unforeseen events beyond the Prevented Party’s reasonable control (an Event of Force Majeure), the Prevented Party shall notify the other Party without delay and within fifteen (15) days thereafter shall provide detailed information concerning such event and documents evidencing such event, explaining the reasons for its inability to execute, or for its delay in the execution of, all or part of its obligations under this Agreement. Service Provider will not be responsible for any lost and damage occurred in Force majeure situation.</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700">ii.	If an Event of Force Majeure occurs, neither Party shall be responsible for any damage,increased costs or loss which the other Party may sustain by reason of such a failure or delay of performance, and such failure or delay shall not be deemed a breach of this Agreement. The Prevented Party shall take reasonable means to minimize or remove the effects of an Event of Force Majeure and, within the shortest reasonable time, attempt to resume performance of the obligations delayed or prevented by the Event of Force Majeure</p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">18) ENTIRE AGREEMENT, ASSIGNMENT AND SURVIVAL</p>


      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        i.	This Agreement, the annexures and any other documents entered into or delivered ascontemplated in this Agreement herein sets out the entire agreement and understanding between the Parties with respect to the subject matter hereof. Unless otherwise decided by
        QUICKPOST, the annexures containing specific terms of use supersedes all general terms of the Agreement, previous letters of intent, heads of terms, prior discussions and correspondence exchanged between the Parties in connection with the Agreement referred to herein. Similarly, unless otherwise decided by QUICKPOST, the SOPs/SLAs issued in furtherance to this Agreement,
        shall supersedes the provisions of this Agreement and of the annexures.

      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        ii.	This Agreement and the rights and obligations herein shall not be assigned by the User,without the consent of QUICKPOST.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        iii.	The provisions which are by their nature, intended to survive the termination of thisAgreement, shall survive the termination of this Agreement.
      </p>

      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">19) GOVERNING LAWS AND JURISDICTION</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        This Agreement, the construction and enforcement of its terms and the interpretation of the rights and duties of the Parties hereto shall be governed by the laws of India and shall be subject to the jurisdiction of courts in New Delhi. This Agreement is executed in English language which shall prevail over any translation thereof.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">20) NO PARTNERSHIP OR AGENCY</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        Nothing in this Agreement (or any of the arrangements contemplated herein) shall be deemed to constitute a partnership between the Parties hereto, nor, except as may be expressly provided herein, constitute any Party as the agent of another Party for any purpose, or entitle any Party to commit or bind another Party in any manner.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">21)WAIVERS AND REMEDIES</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        No failure or delay by the Parties in exercising any right or remedy provided by law under or pursuant to this Agreement shall impair such right or remedy or operate or be construed as a waiver or variation of it or preclude its exercise at any subsequent time and no single or partial exercise of any such right or remedy shall preclude any other or further exercise of it or the exercise of any other right or remedy. The rights and remedies of the Parties under or pursuant to this Agreement are cumulative, may be exercised as often as such Party considers appropriate and are in addition to its rights and remedies under the general laws of India.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">22) MODIFICATION, AMENDMENT, SUPPLEMENT, OR WAIVER</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        i. No modification, amendment, supplement to or waiver of this Agreement or any ofits provisions shall be binding upon the Parties hereto unless made in writing and duly signed by the Parties or Party against whom enforcement thereof is sought. ii. A failure or delay of any Party
        to this Agreement to enforce at any time any of theprovisions of this Agreement or to exercise any option which is herein provided, or to require at any time performance of any of the provisions hereof, shall in no way be construed to be a waiver of such provisions of this Agreement.

      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">23) ENTIRETY OF AGREEMENT</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        This Agreement together with all Recitals, Appendices, Exhibits, Schedules, Attachments, and Addenda attached hereto constitute the entire agreement between the Parties and supersedes all previous agreements, promises, representations, understandings, and negotiations, whether written or oral, between the Parties with respect to the subject matter hereof.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">24) NOTICES</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        Except as may be otherwise provided herein, all notices, requests, waivers and other communications
        (“Notices”) shall be deemed to be delivered as provided herein: (a) if delivered to the addressee
        (“Receiving Party”) by hand: upon the Notice being acknowledged by written receipt by the Receiving Party; (b) if sent by facsimile: upon the receipt of transmission report confirming transmission; (c) if sent via an overnight courier: upon receipt (evidenced by proof of delivery); (d) if sent via electronic mail: upon such email being sent (outgoing mail logs can be provided as proof, as required). The Notices shall be addressed to the Parties at the contact details provided below. Each Party shall promptly inform the other Parties of any change to its contact details.

      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">25) SPECIFIC PERFORMANCE</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        The Parties shall be entitled to seek and enforce specific performance of this Agreement, in addition to any other legal rights and remedies, without the necessity of demonstrating the inadequacy of monetary damages.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">26) SEVERABILITY</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        The invalidity or unenforceability of any provision in this Agreement shall in no way affect the validity or enforceability of any other provision herein. In the event of the invalidity or unenforceability of any provision of this Agreement, the Parties will immediately negotiate in good faith to replace such a provision with another, which is not prohibited or unenforceable and has, as far as possible, the same legal and commercial effect as that which it replaces.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">27) INDIRECT AND CONSEQUENTIAL LOSSES</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        Save as expressly provided otherwise in this Agreement, neither Party shall be liable under or in connection with this Agreement for any loss of income, loss of profits or loss of contracts, or for any indirect or consequential loss or damage of any kind, in each case howsoever arising and whether caused by tort (including negligence), breach of contract or otherwise.
      </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 font-bold">28) CONTACT DETAILS</p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        a.	If any User has any question, issue, complaint regarding any of our Services, please contact
        Company’s customer service at support@QUICKPOST.in
       </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed"> 
        b.	If a User has any questions concerning QUICKPOST, the Services, this Agreement, oranythingrelated to any of the foregoing, it can be reached at the following email address – support@QUICKPOST.in
        </p>
      <p className="text-[10px] sm:text-[12px] text-gray-700 leading-relaxed">
        c.	The User hereby agrees and provides his consent to receive communications,correspondences, updates, notifications, etc. from the Company through email, SMS, WhatsApp and any other mode as agreed by the Parties from time to time. The Parties agree that the said communications, correspondences, updates, notifications, etc. will be legally binding on them. d. Notwithstanding anything provided contrary in this Agreement, the User here by agrees, provides his consent and further authorizes the Company to share his relevant details and documents (including but not limited to business/registered name(s), phone number(s), address(es), email-id(s), bank account details, KYC documents, etc.) with the concerned judicial authority, court, police, complainant, etc. (as the case may be) in the event of a complaint been filed against the User or dispute been raised in relation to the shipment(s) made by the User.

      </p>

    </div>
  );
};

export default Aggrement;
